import type { SetupLanguage, WorkshopSlide } from "../types";

export const SLIDES_COPY = {
  en: [
    {
      eyebrow: "The Next Craft × Vapi",
      title: "Build voice agents that take action.",
      lead: "Today we will make a tiny digital creature hear us, answer us, and change a real product through APIs.",
      statement: "Voice in → actions out → something visible",
      tone: "purple",
    },
    {
      eyebrow: "01 · What is Vapi?",
      title: "The orchestration layer for voice AI.",
      lead: "Vapi connects the realtime pieces of a voice conversation so you can focus on the agent's behavior and your product.",
      flow: ["Listen", "Think", "Speak", "Act"],
      note: "Bring your model, voice, business logic, and APIs. Vapi coordinates the call.",
      tone: "mint",
    },
    {
      eyebrow: "02 · Core concept",
      title: "An assistant is the character and its configuration.",
      lead: "It defines what the agent knows, how it sounds, what it says first, which tools it can use, and where call events go.",
      cards: [
        { eyebrow: "Behavior", title: "System prompt", body: "Identity, goals, rules, and when to use tools." },
        { eyebrow: "Conversation", title: "First message", body: "The opening line that gives the caller direction." },
        { eyebrow: "Realtime stack", title: "Voice + model", body: "Transcriber, reasoning model, and voice provider." },
        { eyebrow: "Connections", title: "Tools + server URL", body: "Actions for the agent and events for your app." },
      ],
      note: "The Assistant ID is the stable link between the dashboard and your VapiGotchi.",
      tone: "paper",
    },
    {
      eyebrow: "03 · Core concept",
      title: "Tools turn conversation into product behavior.",
      lead: "A tool is an action the model may call when the conversation needs data or needs to change something.",
      flow: ["Caller asks", "Model chooses", "HTTP API runs", "Agent responds"],
      cards: [
        { title: "check_vapigotchi", body: "Reads health, mood, name, and meals." },
        { title: "feed_vapigotchi", body: "Feeds the creature and increases its health." },
      ],
      statement: "If your product has an API, your voice agent can use it.",
      tone: "yellow",
    },
    {
      eyebrow: "04 · Build faster",
      title: "Composer configures your assistant with natural language.",
      lead: "Describe the tools you need, review what Composer creates, then test the assistant in the dashboard.",
      flow: ["Describe", "Review", "Test"],
      prompt: "Create two API Request tools. One GET tool checks my VapiGotchi state. One POST tool feeds it with a required food enum. Use these exact URLs…",
      note: "The setup page writes each team's complete prompt. Composer is currently in Alpha, so review every generated change before testing.",
      tone: "pink",
    },
    {
      eyebrow: "05 · Make calls visible",
      title: "Tools change the product. Server events show the call.",
      lead: "Vapi sends call events to your server URL. The page reads lightweight state and turns those events into animations.",
      cards: [
        { title: "status-update", body: "Ringing, in progress, and ended update the live call counter." },
        { title: "speech-update", body: "The creature switches between listening and talking." },
        { title: "Other messages", body: "Acknowledged safely with HTTP 200 and ignored." },
      ],
      flow: ["Vapi webhook", "Pet state", "2-second polling", "Pixel animation"],
      tone: "cyan",
    },
    {
      eyebrow: "06 · Today's build",
      title: "Meet VapiGotchi.",
      lead: "A shared voice creature that changes its name, mood, animation, call counter, and health based on real Vapi events and API tools.",
      cards: [
        { eyebrow: "Talk", title: "Call it", body: "Call Byte or Chorizo on their language-specific numbers." },
        { eyebrow: "Watch", title: "See the call", body: "Ringing, listening, and talking appear live." },
        { eyebrow: "Act", title: "Ask it to eat", body: "A tool call animates food and raises health." },
      ],
      statement: "The voice agent is not the demo. The product reaction is the demo.",
      tone: "purple",
    },
    {
      eyebrow: "07 · Workshop",
      title: "Four steps. One living assistant.",
      lead: "Fork only if you want to remix the app. To connect an assistant, everyone can use the live workshop URL.",
      cards: [
        { eyebrow: "Step 1", title: "Create", body: "Create an assistant and copy the starter prompt + First Message." },
        { eyebrow: "Step 2", title: "Connect", body: "Choose your own pet or the shared language demo, then paste the Server URL." },
        { eyebrow: "Step 3", title: "Add tools", body: "Ask Composer to create both API Request tools." },
        { eyebrow: "Step 4", title: "Call", body: "Open the pet, start a Test call, and ask it to eat." },
      ],
      note: "Use your Assistant ID for an isolated creature. The required path has two tools; salsa, shower, and nap are an optional bonus.",
      tone: "mint",
    },
    {
      eyebrow: "08 · Hackathon challenge",
      title: "Now remix the pattern.",
      lead: "Keep the voice loop. Replace the creature, the tools, or the product state with something your team wants to ship.",
      cards: [
        { title: "Quest master", body: "Voice choices unlock a map, clues, and team progress." },
        { title: "Live storefront", body: "Ask for products and watch a cart update on screen." },
        { title: "Support sidekick", body: "Diagnose a problem and trigger a real workflow." },
        { title: "Multiplayer boss", body: "Many callers use tools against one shared state." },
      ],
      statement: "What can someone say that should make your product move?",
      tone: "yellow",
    },
    {
      eyebrow: "09 · Keep building",
      title: "Resources",
      lead: "Start with the workshop, then use Vapi's agent skills and GitOps workflow to go further.",
      resources: [
        { label: "VapiGotchi", description: "Fork the workshop app and deploy your own creature.", href: "https://github.com/VapiAI/vapi-labs/tree/main/projects/vapigotchi" },
        { label: "Vapi agent skills", description: "Create assistants, tools, calls, squads, and webhooks with your coding agent.", href: "https://github.com/VapiAI/skills" },
        { label: "Vapi GitOps", description: "Manage assistants and tools as version-controlled YAML and Markdown.", href: "https://github.com/VapiAI/gitops" },
        { label: "Workshop reference", description: "Open the event's shared voice agent reference document.", href: "https://docs.google.com/document/d/1-rw2FzWsmjUs1B_L54IULZinrBmPaSON8K-vksHQqGQ/edit?tab=t.r8t498wyccfe#heading=h.wfmxaltvcxr4" },
      ],
      statement: "Make it call. Make it act. Make it visible.",
      tone: "paper",
    },
  ],
  es: [
    {
      eyebrow: "The Next Craft × Vapi",
      title: "Construye agentes de voz que toman acción.",
      lead: "Hoy haremos que una pequeña criatura digital nos escuche, responda y cambie un producto real mediante APIs.",
      statement: "Voz adentro → acciones afuera → algo visible",
      tone: "purple",
    },
    {
      eyebrow: "01 · ¿Qué es Vapi?",
      title: "La capa de orquestación para IA de voz.",
      lead: "Vapi conecta las piezas en tiempo real de una conversación de voz para que te enfoques en el comportamiento del agente y en tu producto.",
      flow: ["Escuchar", "Pensar", "Hablar", "Actuar"],
      note: "Trae tu modelo, voz, lógica de negocio y APIs. Vapi coordina la llamada.",
      tone: "mint",
    },
    {
      eyebrow: "02 · Concepto clave",
      title: "Un assistant es el personaje y su configuración.",
      lead: "Define qué sabe el agente, cómo suena, qué dice primero, qué tools puede usar y a dónde llegan los eventos de llamada.",
      cards: [
        { eyebrow: "Comportamiento", title: "System prompt", body: "Identidad, objetivos, reglas y cuándo usar tools." },
        { eyebrow: "Conversación", title: "First Message", body: "La frase inicial que orienta a quien llama." },
        { eyebrow: "Stack en tiempo real", title: "Voz + modelo", body: "Transcriber, modelo de razonamiento y proveedor de voz." },
        { eyebrow: "Conexiones", title: "Tools + Server URL", body: "Acciones para el agente y eventos para tu app." },
      ],
      note: "El Assistant ID es el vínculo estable entre el dashboard y tu VapiGotchi.",
      tone: "paper",
    },
    {
      eyebrow: "03 · Concepto clave",
      title: "Las tools convierten la conversación en acciones.",
      lead: "Una tool es una acción que el modelo puede llamar cuando la conversación necesita datos o debe cambiar algo.",
      flow: ["Alguien pide", "El modelo elige", "La API ejecuta", "El agente responde"],
      cards: [
        { title: "check_vapigotchi", body: "Lee salud, ánimo, nombre y comidas." },
        { title: "feed_vapigotchi", body: "Alimenta a la criatura y aumenta su salud." },
      ],
      statement: "Si tu producto tiene una API, tu agente de voz puede usarla.",
      tone: "yellow",
    },
    {
      eyebrow: "04 · Construye más rápido",
      title: "Composer configura tu assistant con lenguaje natural.",
      lead: "Describe las tools que necesitas, revisa lo que crea Composer y prueba el assistant en el dashboard.",
      flow: ["Describir", "Revisar", "Probar"],
      prompt: "Crea dos API Request tools. Una tool GET consulta el estado de mi VapiGotchi. Una tool POST lo alimenta usando un enum obligatorio de comidas. Usa exactamente estas URLs…",
      note: "La página de setup escribe el prompt completo de cada equipo. Composer está en Alpha, así que revisa cada cambio antes de probarlo.",
      tone: "pink",
    },
    {
      eyebrow: "05 · Haz visible la llamada",
      title: "Las tools cambian el producto. Los server events muestran la llamada.",
      lead: "Vapi envía eventos de llamada a tu Server URL. La página consulta un estado ligero y convierte esos eventos en animaciones.",
      cards: [
        { title: "status-update", body: "Ringing, in progress y ended actualizan el contador en vivo." },
        { title: "speech-update", body: "La criatura alterna entre escuchar y hablar." },
        { title: "Otros mensajes", body: "Se confirman con HTTP 200 y se ignoran de forma segura." },
      ],
      flow: ["Webhook de Vapi", "Estado", "Polling cada 2 s", "Animación pixel"],
      tone: "cyan",
    },
    {
      eyebrow: "06 · Lo que construiremos",
      title: "Conoce a VapiGotchi.",
      lead: "Una criatura de voz compartida que cambia su nombre, ánimo, animación, contador y salud con eventos reales de Vapi y API tools.",
      cards: [
        { eyebrow: "Habla", title: "Llámala", body: "Llama a Byte o Chorizo en el número correspondiente a su idioma." },
        { eyebrow: "Observa", title: "Mira la llamada", body: "Ringing, listening y talking aparecen en vivo." },
        { eyebrow: "Actúa", title: "Pídele comer", body: "Una tool anima la comida y aumenta su salud." },
      ],
      statement: "El agente de voz no es el demo. La reacción del producto es el demo.",
      tone: "purple",
    },
    {
      eyebrow: "07 · Workshop",
      title: "Cuatro pasos. Un assistant con vida.",
      lead: "Haz fork solo si quieres transformar la app. Para conectar un assistant, todos pueden usar la URL pública del workshop.",
      cards: [
        { eyebrow: "Paso 1", title: "Crear", body: "Crea un assistant y copia el prompt inicial + First Message." },
        { eyebrow: "Paso 2", title: "Conectar", body: "Elige tu mascota o el demo compartido del idioma y pega la Server URL." },
        { eyebrow: "Paso 3", title: "Agregar tools", body: "Pide a Composer que cree las dos API Request tools." },
        { eyebrow: "Paso 4", title: "Llamar", body: "Abre la mascota, inicia un Test call y pídele comer." },
      ],
      note: "Usa tu Assistant ID para una criatura aislada. El camino principal tiene dos tools; salsa, ducha y siesta son un bonus opcional.",
      tone: "mint",
    },
    {
      eyebrow: "08 · Reto del hackathon",
      title: "Ahora transforma el patrón.",
      lead: "Mantén el loop de voz. Reemplaza la criatura, las tools o el estado por algo que tu equipo quiera lanzar.",
      cards: [
        { title: "Maestro de misiones", body: "Las decisiones por voz desbloquean mapa, pistas y progreso." },
        { title: "Tienda en vivo", body: "Pide productos y mira cómo cambia un carrito en pantalla." },
        { title: "Compañero de soporte", body: "Diagnostica un problema y dispara un workflow real." },
        { title: "Boss multijugador", body: "Muchas llamadas usan tools contra un estado compartido." },
      ],
      statement: "¿Qué puede decir alguien que debería hacer que tu producto se mueva?",
      tone: "yellow",
    },
    {
      eyebrow: "09 · Sigue construyendo",
      title: "Recursos",
      lead: "Comienza con el workshop y luego usa las agent skills y GitOps de Vapi para llegar más lejos.",
      resources: [
        { label: "VapiGotchi", description: "Haz fork de la app del workshop y despliega tu propia criatura.", href: "https://github.com/VapiAI/vapi-labs/tree/main/projects/vapigotchi" },
        { label: "Agent skills de Vapi", description: "Crea assistants, tools, llamadas, squads y webhooks con tu coding agent.", href: "https://github.com/VapiAI/skills" },
        { label: "Vapi GitOps", description: "Administra assistants y tools como YAML y Markdown con control de versiones.", href: "https://github.com/VapiAI/gitops" },
        { label: "Referencia del workshop", description: "Abre el documento compartido de referencia sobre agentes de voz.", href: "https://docs.google.com/document/d/1-rw2FzWsmjUs1B_L54IULZinrBmPaSON8K-vksHQqGQ/edit?tab=t.r8t498wyccfe#heading=h.wfmxaltvcxr4" },
      ],
      statement: "Haz que llame. Haz que actúe. Hazlo visible.",
      tone: "paper",
    },
  ],
} satisfies { [Language in SetupLanguage]: readonly WorkshopSlide[] };
