import type { SetupLanguage } from "./types";

export const HOME_COPY = {
  en: {
    languageLabel: "Homepage language",
    nav: {
      label: "Main navigation",
      livePet: "Live pet",
      buildYours: "Build yours",
      slides: "Slides",
    },
    hero: {
      kicker: "A Vapi workshop project",
      title: "A voice agent you can see come alive.",
      emphasis: "see",
      description:
        "Call Byte, feed it, or ask it to dance salsa, shower, and nap. Every voice event and API tool call becomes a live pixel animation.",
      callLabel: "Call Byte in English",
      callAction: "Call now →",
      toolChip: "API TOOL ✓",
      meetPet: "Meet Byte ↓",
      buildOwn: "Build your own",
      copyPetUrl: "Copy Byte's live URL",
      copiedPetUrl: "Byte's URL copied!",
    },
    pet: {
      languageLabel: "Live pet language",
      eyebrow: "Live voice creature",
      idLabel: "ID",
      reconnecting: "Reconnecting",
      live: "Live",
      status: {
        eating: "Eating",
        dancing: "Dancing salsa",
        showering: "Taking a shower",
        napping: "Taking a nap",
        talking: "Talking to a human",
        listening: "Listening carefully",
        ringing: "The phone is ringing",
        onCall: "On a live call",
        weak: "Needs a snack",
        hungry: "Getting hungry",
        happy: "Feeling fantastic",
        idle: "Waiting for a call",
      },
      food: {
        apple: "apple",
        pizza: "pizza",
        burger: "burger",
        sushi: "sushi",
        bagel: "bagel",
        "protein-shake": "protein shake",
        sandwich: "sandwich",
        empanada: "empanada",
        ramen: "ramen",
        soup: "soup",
        burrito: "burrito",
        "filet-mignon": "filet mignon",
        chicken: "chicken",
        cheese: "cheese",
        tomato: "tomato",
        taco: "taco",
        arepa: "arepa",
        pupusa: "pupusa",
        ceviche: "ceviche",
      },
      loading: "Waking up...",
      health: "Health",
      healthAria: "Health",
      outOf: "out of",
      ringing: "ringing",
      connected: "connected",
      speaking: "speaking",
      liveCall: "live call",
      liveCalls: "live calls",
      mealsEaten: "Meals eaten",
      privacy: "No transcripts, names, or phone numbers are stored.",
      imageAria: "VapiGotchi is",
      callEyebrow: "Call the English VapiGotchi",
      callTitle: "+1 (659) 399 0187",
      callDescription:
        "Ask how Byte feels, tell it what to eat, or ask it to dance salsa, shower, and nap. Watch every action happen live.",
      callAction: "Call now",
      footerPrompt: "Want a creature for your own Vapi assistant?",
      footerAction: "Generate your pet URLs →",
    },
    architecture: {
      eyebrow: "The tiny architecture",
      title: "Voice in. Actions out. One very happy creature.",
      steps: [
        {
          number: "01",
          title: "Call",
          description: "Vapi handles the realtime voice conversation.",
        },
        {
          number: "02",
          title: "Act",
          description: "The assistant calls a regular HTTP API tool.",
        },
        {
          number: "03",
          title: "Watch",
          description: "The page polls lightweight state and animates it live.",
        },
      ],
      action: "Connect your assistant →",
    },
  },
  es: {
    languageLabel: "Idioma de la página principal",
    nav: {
      label: "Navegación principal",
      livePet: "Mascota en vivo",
      buildYours: "Construye la tuya",
      slides: "Slides",
    },
    hero: {
      kicker: "Un proyecto para un workshop de Vapi",
      title: "Un agente de voz que puedes ver cobrar vida.",
      emphasis: "ver",
      description:
        "Llama a Chorizo y pídele comer, bailar salsa, ducharse o tomar una siesta. Cada tool call se convierte en una animación pixelada en vivo.",
      callLabel: "Habla con Chorizo en español",
      callAction: "Llamar ahora →",
      toolChip: "TOOL DE API ✓",
      meetPet: "Conoce a Chorizo ↓",
      buildOwn: "Construye el tuyo",
      copyPetUrl: "Copiar URL de Chorizo",
      copiedPetUrl: "¡URL de Chorizo copiada!",
    },
    pet: {
      languageLabel: "Idioma de la mascota en vivo",
      eyebrow: "Criatura de voz en vivo",
      idLabel: "ID",
      reconnecting: "Reconectando",
      live: "En vivo",
      status: {
        eating: "Comiendo",
        dancing: "Bailando salsa",
        showering: "Dándose una ducha",
        napping: "Tomando una siesta",
        talking: "Hablando con una persona",
        listening: "Escuchando atentamente",
        ringing: "El teléfono está sonando",
        onCall: "En una llamada en vivo",
        weak: "Necesita un snack",
        hungry: "Le está dando hambre",
        happy: "Se siente increíble",
        idle: "Esperando una llamada",
      },
      food: {
        apple: "manzana",
        pizza: "pizza",
        burger: "hamburguesa",
        sushi: "sushi",
        bagel: "bagel",
        "protein-shake": "batido de proteína",
        sandwich: "sándwich",
        empanada: "empanada",
        ramen: "ramen",
        soup: "sopa",
        burrito: "burrito",
        "filet-mignon": "filete miñón",
        chicken: "pollo",
        cheese: "queso",
        tomato: "tomate",
        taco: "taco",
        arepa: "arepa",
        pupusa: "pupusa",
        ceviche: "ceviche",
      },
      loading: "Despertando...",
      health: "Salud",
      healthAria: "Salud",
      outOf: "de",
      ringing: "sonando",
      connected: "conectada",
      speaking: "hablando",
      liveCall: "llamada en vivo",
      liveCalls: "llamadas en vivo",
      mealsEaten: "Comidas",
      privacy: "No guardamos transcripciones, nombres ni teléfonos.",
      imageAria: "VapiGotchi está",
      callEyebrow: "Habla con Chorizo en español",
      callTitle: "+1 (984) 305 5885",
      callDescription:
        "Pregúntale cómo se siente, qué quiere comer o pídele bailar salsa, ducharse y tomar una siesta. Mira cada acción en vivo.",
      callAction: "Llamar ahora",
      footerPrompt: "¿Quieres una criatura para tu propio asistente de Vapi?",
      footerAction: "Genera las URLs de tu mascota →",
    },
    architecture: {
      eyebrow: "La pequeña arquitectura",
      title: "Entra voz. Salen acciones. Una criatura muy feliz.",
      steps: [
        {
          number: "01",
          title: "Llama",
          description: "Vapi maneja la conversación de voz en tiempo real.",
        },
        {
          number: "02",
          title: "Actúa",
          description:
            "El asistente llama una herramienta que usa una API HTTP normal.",
        },
        {
          number: "03",
          title: "Observa",
          description:
            "La página consulta un estado liviano y lo anima en vivo.",
        },
      ],
      action: "Conecta tu asistente →",
    },
  },
} as const satisfies Record<SetupLanguage, unknown>;
